### PR TITLE
Fix calculations and hard-code less

### LINKED ISSUE #12: Wrong sizes on high resolution screens
The math seems to be off on high resolution screens, 3840x2160 in my case. I believe I have also tried this on a 2560x1440 screen without any issues, but it has been a while since I had that hooked up, so I am not quite sure anymore.

Emacs does some weird calling for high resolutions. Again, I don't remember any details but for my `moody` package I got the `create-image` to stop calling by some unknown number by telling it to scale by 1 instead, using `(create-image ... :scale 1)`.

Note that it's not just the font size that is off, there also appear some pixels to be missing at the bottom of images.

### PR DESCRIPTION
**Pull request by tarsius**
Closes #12.

All but the last commit perform some cleanup.  The last commit makes the big changes.  I could have tried to split that into multiple commits, but don't think the work involved in that would be worth it.

There were four major issues:

1. `image-compute-scaling-factor` was not taken into account.  (While that says "image", the same factor applies to faces.)
2. Calls to `face-attribute` did not use the `inherit` property, which lead to lots of duplication, complications and probably some bugs.
3. Likely in order to deal with issues caused by (1) and (2) fonts were hard-coded, hiding issues and increasing the likelihood this breaks completely for many users (who don't have the font installed).
4. The calculations seemed a bit obfuscated at times.  ;)

I'll probably be adding `svg-tag--make` to forge (under a different name of course ;) and use it for labels.  Or maybe even for refnames in magit.  That's why I looked into `svg-tag-mode` in the first place!

### CODE REVIEW

**Comment by tarsius** [comment]
Uh, I should not that I have not tested this much. I drafed this code and then let it sit back when I brought up the issue; and how I have cleaned it up a bit because of the activity in #12.

**Comment by jamesnvc** [comment]
This seems to work for me!

**Comment by rougier** [comment]
Thank you! Impressive, I've a lot to learn . I'll test it on my side but if no complaints, I'll merge.

**Comment by jamesnvc** [comment]
I'm very curious how the drawing works internally...I continue to see that omitting the `:font-size` in the call to `svg-text` makes the text show as the correct size (in conjunction with changing the text-y to `(- txt-height 5)` instead of `font-size`), while normally it's way too small and in the top-left corner. I don't know if it's worth trying to figure out what calculation is needed -- maybe it's just my weird setup that necessitates this -- or just set a much-larger font size for the svg face.

**Comment by rougier** [comment]
Could post some screenshots showing the problem?

**Comment by jamesnvc** [comment]
Opening `example-2.el` & eval-ing with `emacs -Q`:
screenshot-2021-04-30_15-50-49

Commenting out the `:font-size` line in `svg-tag--make` and repeating:
screenshot-2021-04-30_15-59-25

Commenting out `:font-size` and changing `(text-y font-size)` to `(text-y (- txt-height 5))` in `svg-tag--make`:
screenshot-2021-04-30_16-00-24

**Comment by rougier** [comment]
What does `(frame-monitor-attributes)` returns ?

**Comment by tarsius** [comment]
Well, it seems my calculations and/or there are values I am not taking into account are off too. :/

So I very much welcome it if other people also try to figure out why it doesn't work for them.

For debugging purposes I recommend editing `svg-tag--make` to return `svg` instead of `(svg-image svg ...)` and pretty-print the value.

**Comment by jamesnvc** [comment]
> What does (frame-monitor-attributes) returns ?

```elisp
((name . "DP-1") (geometry 0 0 3840 2160) (workarea 0 0 3840 2160)
 (mm-size 610 350) 
 (frames #<frame *scratch* - GNU Emacs at gonk 0x56359771c210>) (source . "Gdk"))
```

> Well, it seems my calculations and/or there are values I am not taking into account are off too. :/

It is entirely possible I've just done something so bizarre with my DPI settings that Emacs is doing the wrong thing somewhere...although I do find it suspicious that not passing `:font-size` to `svg-text` does the right thing.

The value of `svg` seems reasonable enough; for example, this is `svg-tag-org-todo` from `example-2.el`:

```elisp

(svg 
 ((width . 60) (height . 23) 
  (version . "1.1") (xmlns . "http://www.w3.org/2000/svg")
  (xmlns:xlink . "http://www.w3.org/1999/xlink"))
 (rect
  ((width . 50) (height . 21)
   (x . 5.0) (y . 0) (rx . 2)
   (fill . "#FFAB91")))
 (rect
  ((width . 49.0) (height . 20.0)
   (x . 5.5) (y . 0.5)
   (rx . 1.5) (fill . "#FFAB91")))
 (text
  ((y . 10.040268456375841) (x . 10.0)
   (fill . "#ffffff") (font-size . 10.040268456375841)
   (font-weight) (font-family . "PragmataPro Liga"))
  "TODO"))
```

**Comment by rougier** [comment]
From https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/font-size, it seems the default `font-size` is `medium`. Can you try specifying this font size and check if you get the same result as when not specifying the font size?

**Comment by jamesnvc** [comment]
Hm, `"medium"` seems to make the text too big:

screenshot-2021-05-03_09-18-10

I did note that setting the font-size to be `"1em"` appears to be the correct size, albeit misaligned vertically:

screenshot-2021-05-03_09-19-49

**Comment by rougier** [comment]
Interesting. I'm not sure how Emacs or librsvg computes the 1em. Do you know which svg library your emacs is using?
For the vertical alignment, I think it might be font dependent and there nothing much we can dot but adapt manually the offset.

**Comment by jamesnvc** [comment]
> Do you know which svg library your emacs is using?

Looks like librsvg2 2.48.9 (I've built it myself from git). 

> I'm not sure how Emacs or librsvg computes the 1em

Reading `svg_load_image` in `image.c`, it seems like it pretty much just passes the content to rsvg. I'll have a look at rsvg and see if I can figure out what it's doing.

>  For the vertical alignment, I think it might be font dependent and there nothing much we can dot but adapt manually the offset.

Yeah...might be able to compute something from `window-font-height`?

**Comment by jamesnvc** [comment]
Ah, I see that it injects CSS into the SVG that sets a default font-size and font-family from the face used to display the image. Unsure then why it's different from the font-size set on the text element...

**Comment by jamesnvc** [comment]
Another interesting data point; I tried setting the font size in `pt` (instead of unsuffixed which will be pixels) and now it renders differently in Firefox and Emacs:

Firefox: screenshot-2021-05-03_12-54-14

Emacs: 
screenshot-2021-05-03_12-54-33

svg:
```xml
<svg width="60" height="23" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
  <rect width="50" height="21" x="5.0" y="0" rx="2" fill="#FFAB91"></rect>
  <rect width="49.0" height="20.0" x="5.5" y="0.5" rx="1.5" fill="#FFAB91"></rect>
  <text y="10.053691275167786pt" x="10.0pt" fill="#ffffff" font-size="10.053691275167786pt" font-weight="nil" font-family="PragmataPro Liga">
    TODO
  </text>
</svg>
```

**Comment by rougier** [comment]
librsvg seems to have suffered from dpi problems (https://gitlab.gnome.org/GNOME/librsvg/-/issues/427) but I don't know if this is related.

**Comment by jamesnvc** [comment]
I do see calls to `rsvg_handle_set_dpi_x_y` which I assume are to address DPI issues, but maybe the text drawing does something different with those...

**Comment by jamesnvc** [comment]
I see there was an issue in Emacs' svg rendering on high-dpi screens, but it was apparently resolved: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=45124

**Comment by jamesnvc** [comment]
I have something working by taking a somewhat different approach -- calculating the font size in ems instead of pixels. Setting the text-y still needs some fiddling though...does this work for other folks?

```diff
diff --git a/svg-tag-mode.el b/svg-tag-mode.el
index 49cca62..5e80a3d 100644
--- a/svg-tag-mode.el
+++ b/svg-tag-mode.el
@@ -141,14 +141,15 @@ (defun svg-tag--make (text face padding margin radius)
          (text-x      (+ tag-x
                          (/ (- tag-width (* (length text) txt-width))
                             2)))
-         (font-size   (* (ceiling
-                          (* (face-attribute face :height nil 'default)
-                             0.1))
-                         (image-compute-scaling-factor 'auto)))
-         (txt-height  (window-font-height))
+         (font-size   (format "%sem"
+                              (ceiling
+                               (* (/ (face-attribute face :height nil 'default)
+                                     (face-attribute 'default :height nil))
+                                  0.1))))
+         (txt-height  (window-font-height nil face))
          (svg-height  txt-height)
          (tag-height  (- txt-height 2))
-         (text-y      font-size)
+         (text-y      (- txt-height 5))
          (svg         (svg-create svg-width svg-height)))
     (svg-rectangle svg tag-x 0 tag-width tag-height
                    :fill (if box box-color background)
```

**Comment by jamesnvc** [comment]
I confess myself very confused. I would love to see what this looks like on other OSes & DPIs; right now, I'm just not sure where to look.

**Comment by rougier** [comment]
Another try below. I'm able to extract the ascent and descent that should fix the position of the text but the pixel size is wrong for me. I set the default size to "140" in Emacs but the reading of the pixel size returns me 8.

Can you check the code below on your side (you'll need to adapt font size until we find where we can read this value):


```
;; See www.gnu.org/software/emacs/manual/html_node/elisp/Low_002dLevel-Font.html
;;
;; Pixel size
;; (elt (query-font (font-at (point-min))) 3)
;;  -> This is wrong for me (return 8 instead of 14)
;;
;; Descent
;; (elt (query-font (font-at (point-min))) 4)
;;
;; Ascent
;; (elt (query-font (font-at (point-min))) 5)
;;
;; Average width
;; (elt (query-font (font-at (point-min))) 5)



(let* ((text       "Hello guys!")

       ;; This should correspond the size of your default face
       (font-size  14)
       ;; (elt (query-font (font-at (point-min))) 3)
        
       (descent    (elt (query-font (font-at (point-min))) 4))
       (ascent     (elt (query-font (font-at (point-min))) 5))
       (svg-height (+ ascent descent))
       (char-width (elt (query-font (font-at (point-min))) 7))
       (svg-width  (* char-width (length text)))
       (svg        (svg-create svg-width svg-height)))
   
  (svg-text svg text
            :fill "black"
            :stroke-width 0
            :font-family "Roboto Mono"
            :font-weight "300"
            :font-size   font-size
            :x 0
            :y descent)
  (insert-image (svg-image svg :ascent 'center)))

```

**Comment by rougier** [comment]
Also, can you try `(/ (display-pixel-width) (/ (display-mm-width) 25.4))` (this should returns the dpi as seen by emacs)

**Comment by jamesnvc** [comment]
> Can you check the code below on your side

When I up the font-size to 20 (where my font is actually set to 9) it looks perfect.

> can you try `(/ (display-pixel-width) (/ (display-mm-width) 25.4))`

That gives me 159.112..., which seems pretty much correct (actual DPI 159)

**Comment by rougier** [comment]
I suspect that the SVG uses a DPI of 72 instead of actual DPI. In your case, 9 would need to be multiplied by 159/72 ~ 2.2. But more generally, I think this means we need to set the viewBox properly and this should solve all our problem. But I'm not quite sure what is the right value for the viewbox.

**Comment by rougier** [comment]
Could you test code below and play with font size (`text-scale-adjust`) to check if it is working properly ? 

```
(let* ((text "Hello guys!")
       (font-dpi 72.272) ;; see https://en.wikipedia.org/wiki/Point_(typography)
       (screen-dpi  (/ (display-pixel-width) (/ (display-mm-width) 25.4)))
       (font-size (elt (query-font (font-at (point-min))) 3))
       (font-size (truncate (* font-size (/ screen-dpi font-dpi))))
       (descent    (elt (query-font (font-at (point-min))) 4))
       (ascent     (elt (query-font (font-at (point-min))) 5))
       (svg-height (+ ascent descent))
       (char-width (elt (query-font (font-at (point-min))) 7))
       (svg-width  (* char-width (length text)))
       (svg        (svg-create svg-width svg-height)))
  (svg-text svg text
            :fill "black"
            :stroke-width 0
            :font-family "Roboto Mono"
            :font-weight "300"
            :font-size font-size
            :x 0
            :y descent)
  (insert-image (svg-image svg :ascent 'center)))
```

**Comment by jamesnvc** [comment]
> Could you test code below and play with font size

Hm, it seems slightly too large for me, truncating the exclamation mark, but consistent with different font sizes.

Original:
screenshot-2021-05-16_10-24-29

Scaled up a bunch:
screenshot-2021-05-16_10-24-40

Scaled down a bunch:
screenshot-2021-05-16_10-24-51

**Comment by jamesnvc** [comment]
Hm, I see though that `(elt (query-font (font-at (point-min))) 3)` gives `10`, but I have my default font set to `9`, which seems like that would cause the different size :/

**Comment by rougier** [comment]
How do you set the initial size of your font in your .emacs?

**Comment by jamesnvc** [comment]
> How do you set the initial size of your font in your .emacs?

`(set-frame-font "PragmataPro Liga 9" nil t)`

**Comment by rougier** [comment]
And if you try to customize face `default`, what is the height ?

**Comment by jamesnvc** [comment]
> And if you try to customize face default, what is the height ?

91 - so I guess this font is just tall enough that it gets rounded up or something? Weird...

**Comment by rougier** [comment]
Ok, maybe we can use `(/ (face-attribute 'default :height) 10)` for font-size. When it is an integer, size is expressed in 1/10 of pt. But for me, this value is 14 wich is the right value fot the svg (without dpi conversion).

**Comment by jamesnvc** [comment]
I just tried using the `face-attribute` method, but then it doesn't work properly with `text-scale-adjust`, although it is okay normally.

**Comment by rougier** [comment]
That is expected. When you scale manually a buffer, it does not change the face.

**Comment by rougier** [comment]
What is the output of `(display-monitor-attributes-list)` ?

**Comment by jamesnvc** [comment]
```elisp

(((name . "DP-1")
  (geometry 0 0 3840 2160)
  (workarea 0 0 3840 2160)
  (mm-size 610 350)
  (frames #<frame /home/james/org/todo.org 0x55e7ece72890> #<frame *scratch* 0x55e7ede43320> #<frame /home/james/Projects/writing/_drafts/braindump4.org 0x55e7f104d2f8> #<frame /home/james/src/terminusdb-client-python/terminusdb_client/woqlquery/woql_query.py 0x55e7f7a101f0> #<frame  0x55e7f3e23b70> #<frame /home/james/org/Raj_work.org 0x55e801d05008> #<frame *scratch* 0x55e803854ef0> #<frame  0x55e804679f40> #<frame braindump4.org 0x55e804ede448> #<frame *eshell*<4> 0x55e806ef7c10>)
  (source . "Gdk")))
```

**Comment by rougier** [comment]
So maybe we can use both value to compute scaling factor. What do you get from these two lines?

```
(/ (face-attribute 'default :height) 10)                   ;; For 14 (screen pt?)
(elt (query-font (face-attribute 'default :font)) 3) ;; For me 8 (font pt ?)
```

**Comment by jamesnvc** [comment]
> `(/ (face-attribute 'default :height) 10)`

9

> `(elt (query-font (face-attribute 'default :font)) 3)`

10

**Comment by rougier** [comment]
I'm a bit lost. I need to find how emacs convert pt to pixels. But given your dpi and the size you get, your font should be really tiny on screen and from your screenshot, it does not seem to be the case. Do you know if gtk might interfere with the rendering? Like a global scaling factor?

**Comment by rougier** [comment]
For example: https://wiki.archlinux.org/title/HiDPI#Fractional_scaling

**Comment by rougier** [comment]
Can you try (on the command line): `GDK_SCALE= emacs` (from https://github.com/syl20bnr/spacemacs/issues/8770)

**Comment by jamesnvc** [comment]
> Do you know if gtk might interfere with the rendering?

Extremely possible...I think I have some GTK scaling setting, but I set this machine up quite a few years ago.

`GDK_SCALE=` didn't do anything, but I see I also have `org.gnome.desktop.interface text-scaling-factor` set. Resetting it didn't seem to do anything, but I'll try restarting and see if that changed anything...

**Comment by rougier** [comment]
Try https://github.com/wbolster/emacs-gsettings/blob/master/gsettings.el

**Comment by jamesnvc** [comment]
I have no idea what's happening on my computer now 😅 

Changing the gsettings text-scaling-factor didn't seem to affect anything. Somehow after restarting, Emacs font rendering seems the same, the window decoration font is now rendering much thicker. About ready to just nuke my installation and start from scratch...

**Comment by deb75** [comment]
From [this comment](https://github.com/rougier/svg-tag-mode/issues/12#issuecomment-846057023) and the following answeer, here is the result of the test : 
capture

**Comment by rougier** [comment]
What is the height of the default face?

**Comment by deb75** [comment]
Hi,

The default font is "bitstream vera sans mono", I do not know how to retrieve its height.

**Comment by rougier** [comment]
`M-: (face-attribute 'default :height)`

**Comment by deb75** [comment]
Thanks, this command gives : 
```
139 (#o213, #x8b)
``

**Comment by rougier** [comment]
Ok. Can you try with `font-size 14` in the svg part (instead of `font-size font-size`) ? Hoepfully, this should fix the display.

**Comment by deb75** [comment]
Here is what I get with `font-size 14`

capture3

Is it the expected result ? From my earlier post, I have to increase the font size up to 48. But 14 is exactly the font I use in emacs, from my config : 
```lisp
  (set-frame-font "Bitstream Vera Sans Mono-14")
  (add-to-list 'default-frame-alist '(font . "Bitstream Vera Sans Mono-14")))
```

**Comment by rougier** [comment]
Not the expected result. But the displayed text seems to be more or less 14 pixels height while the text is emacs might be much bigger. Probably a HiDPI thing. What is your system? Do you know if you have some settings for HiDPI?

**Comment by deb75** [comment]
Hello,

Indeed, my screen is hidpi (3000x2000), approximately 290dpi.

In both os, windows 10 and linux, I have to use the screen scale option, 250% for windows, 200% for linux.

**Comment by rougier** [comment]
What do you get from `(font-info "Roboto Mono:14")` (maybe replace `Roboto Mono` with `(face-attribute 'default :family)`)

**Comment by tarsius** [comment]
As a side-note: For now at least I have decided against using svg to render the topic labels in the forge package. If anyone is interested, I have pushed to experimental code to the `svg-topic-labels` branch.

**Comment by rougier** [comment]
@tarsius And for those interested, [svg-lib](https://github.com/rougier/svg-lib) might be more robust.

**Comment by deb75** [comment]
Hi,

Thanks for pointing out this.

It have tested most of the examples in the demo. It works nice on `emacs / windows 10`.

However, I still have to manually increase the `font-size` field up to 40 and also, to tweak `padding`, `stroke` fields
in order to get a similar visual appealing aspect. I guess the scaling on hidpi  screens, either windows or linux, still messes up somewhere.

That said, it is not a too annoying issue because the `svg-lib` functions provide all the necessary parameters to adapt to the screen, as far as I have tested.

It would be nice if you could provide a more detailed documentation or example of all the functions parameters and what they are doing. Also, in the last exemple (`svg-lib-icon`), is it possible to provide the (file) path or icon ? or to provide a directory search path where to find icons ?

Thanks very much for providing this library.

Regards

**Comment by rougier** [comment]
@deb75 Thansk for the report and ideas. I should have included a local repo for icons and have options to adjust font size. Can you open issues on the svg lib repo? In the end, I would like to understand the HiDPI stuff such that no tweaking would be necessary but I ran out of ideas. I need to find a windows machine to test.

**Comment by pstray** [comment]
Using (font-dpi 96) in the code above seems to work fine here... the image and the default text seems identical.
I am using "DejaVuSansMono Nerd Font Mono-8" on a 1920x1080, 280mm x 160mm, so about 173.5 ppi.

**Comment by rougier** [comment]
Thanks for the report. What is the code you're referring exactly (there's too much code in this issue). Also, how did you find the dpi that works ? Is i reported by Emacs somewhere?

**Comment by pstray** [comment]
That would be your code from https://github.com/rougier/svg-tag-mode/pull/14#issuecomment-841776885

I tried 96 (as that is the default dpi set by most stuff nowadays it seems), after both higher and lower values, but 96 did get me the exact same width in the image inserted as in the same text on the next line in my emacs buffer.

It also works with 96 in my other laptop while docked on a 2560x1440 (597mm x 336mm) screen, so 108.9 ppi there...

The values emacs reports is (display-pixel-height) => 1440 and (display-mm-height) => 220 (the laptop-screen itself) which gives 166 ppi, which is also the value i have set for the Xresource Xft.dpi and given to xrandr --dpi.

Btw, 72.27 seems to only be used in typesetting, I have never encountered it on a computer (exept maybe in some TeX code)... 72 on the other hand, is pretty common, as used in PostScript and PDF amongst other things.

On the other hand, if i just use the following code, it works just fine (not that i use the PIXEL-SIZE element of the font-query)
```
(let* ((text "Hello guys!")
       (font       (query-font (font-at (point-min))))
       (font-size  (elt font 2))
       (family     (face-attribute 'default :family))
       (descent    (elt font 4))
       (ascent     (elt font 5))
       (svg-height (+ ascent descent))
       (char-width (elt (query-font (font-at (point-min))) 7))
       (svg-width  (* char-width (length text)))
       (svg        (svg-create svg-width svg-height)))
  (svg-text svg text
            :fill "white"
            :stroke-width 0
            :font-family family
            :font-weight "300"
            :font-size font-size
            :x 0
            :y descent)
  (insert-image (svg-image svg :ascent 'center)))
```

**Comment by rougier** [comment]
Thansk for the report and sorry for the delay. The fact that the code you provide doesn't need dpi is nice and may solve a lot of hassle. I think it corresponds more or less to what I did for [svg-lib](https://github.com/rougier/svg-lib). In the end, I wonder where the dpi problem comes from when it occurs.

**Comment by aru-hackZ** [comment]
Hey all, after been testing a bit, I decided to remake `svg-tag--make` calculations, and seems like I hit the jackpot and it works perfectly with the aligning (tho not horizontally since to do that you would have to remove the padding option and make the text align at the center of the tag, so maybe you could still have an option for min-padding, this is something I'm planning to make).

What I dont know is if it will work for everyone, I tried with some fonts and worked for me, here is the code for the function:

```emacs-lisp
(defun svg-tag--make (text face padding margin radius)
  (let* ((foreground   (face-attribute face :foreground nil t))
         (background   (face-attribute face :background nil t))
         (box          (face-attribute face :box nil t))
         (box          (if (eq box 'unspecified) nil box))
         (border-color (or (plist-get box :color) foreground))
         (border-width (or (plist-get box :line-width) 0))
         (font-family  (face-attribute face :family nil 'default))
         (font-weight  (alist-get (face-attribute face :weight nil 'default)
				  svg-tag--font-weights))
	 (char-width   (window-font-width))
	 (char-height  (window-font-height))
	 (text-width   (* char-width (length text)))
	 (tag-width    (+ text-width (* padding 2)))
	 (box-width    (+ tag-width (* border-width 2)))
	 (box-height   (- char-height 2))
	 (tag-height   (- box-height (* border-width 2)))
	 (tag-x        (+ margin border-width))
	 (tag-y        (+ border-width 1))
	 (svg-width    (+ box-width (* margin 2)))
         (text-size    (* (ceiling
			   (* (face-attribute face :height nil 'default)
			      0.1))
			  (image-compute-scaling-factor 'auto)))
	 (text-x       (+ tag-x padding))
	 (text-y       (+ text-size (/ (- box-height (* (/ text-size 3.0) 4)) 2) border-width))
         (svg         (svg-create svg-width char-height)))
    (svg-rectangle svg margin 1 box-width box-height
                   :fill (if box border-color background)
                   :rx   radius)
    (when box
      (svg-rectangle svg
		     tag-x tag-y tag-width tag-height
                     :fill background
                     :rx   radius))
    (svg-text svg text
              :font-family font-family
              :font-weight font-weight
              :font-size   text-size
              :fill        foreground
              :x           text-x
              :y           text-y)
    (svg-image svg :scale 1 :ascent 'center)))
```

And here is a ss of how it looks
Sun-12-Dec-2021_12-09-00

And here with a larger font (from 120 height before to 180 here):
Sun-12-Dec-2021_12-18-36
It seems like the text is a bit bigger, but feels a bit small, tho it still aligns vertically at the center.

Hope this helps

**Comment by aru-hackZ** [comment]
Here is how to make the text stay at the center of the box (horizontally), we could make it by default like this or with a bool argument.

This is the only thing to change to make it work:
```emacs-lisp
(text-x (+ tag-x
           padding
           (/ (- text-width
                 (* (/ (float char-width)
                        char-height)
                    (* (/ text-size
                          3.0)
                       4)
                    (length text)))
              2)))
```

And here a ss:
Sun-12-Dec-2021_12-59-34

Im now working in fixing the width, so it stays the same as the normal text

**Comment by aru-hackZ** [comment]
Here is the fix for the width:

```emacs-lisp
(total-width  (+ text-width (* padding 2) (* margin 2) (* border-width 2)))
(svg-width    (if (= (mod total-width
                          char-width)
                     0)
                  total-width
                (* (+ 1
                      (truncate (/ total-width
                                   char-width)))
                   char-width)))
(box-width    (- svg-width (* margin 2)))
(tag-width    (- box-width (* border-width 2)))
```

And if you want centered text with the above fix:
```emacs-lisp
         (text-x       (+ tag-x
                          padding
                          (/ (- tag-width
                                (* padding 2)
                                (* (/ (float char-width)
                                      char-height)
                                   (* (/ text-size
                                         3.0)
                                      4)
                                   (length text)))
                             2)))
```

In the centering of the text, the padding could be better called as a min-padding, since the text will separate from it so it is centered.

Here is a ss:
Sun-12-Dec-2021_14-04-55

Should I make a pr to add the code or do you add it yourself @tarsius ? Since this pr is related to calculations too.

**Comment by tarsius** [comment]
@aru-hackZ, open a new pr.

Also, should this pr be closed, @rougier? I don't plan to work on it anymore. It seems things have moved beyond what we have here. Code-wise that is, it still seems like a place to have a conversation, so maybe it should stay open.

**Comment by aru-hackZ** [comment]
> @aru-hackZ, open a new pr.

Then I would like if this pr was merged, since the code I worked on was with yours as its base.

**Comment by tarsius** [comment]
Just include my commit in your pr. :grinning: 

(But of course one could first merge this too. In any case you don't have to wait for this to be merged before opening your pr.)

**Comment by aru-hackZ** [comment]
I think I will wait for the pr to be merged first.

**Comment by rougier** [comment]
Thank for the code and I'll need to test it a bit further.  As or merging, it might be better to merge it in [svg-lib](https://github.com/rougier/svg-lib) which is now part of ELPA (and also have a `svg-lib-tag` which share most  of the code). Could you post below you full code (with example) or a link to a git?

**Comment by aru-hackZ** [comment]
The new calculations I made, as I said, were based on the code tarsius has on his fork, so you would need to first merge his PR, the final code I had (which also aligns the text in the center of the tag) is this:

```emacs-lisp
(defun svg-tag--make (text face padding margin radius)
  (let* ((foreground   (face-attribute face :foreground nil t))
         (background   (face-attribute face :background nil t))
         (box          (face-attribute face :box nil t))
         (box          (if (eq box 'unspecified) nil box))
         (border-color (or (plist-get box :color) foreground))
         (border-width (or (plist-get box :line-width) 0))
         (font-family  (face-attribute face :family nil 'default))
         (font-weight  (alist-get (face-attribute face :weight nil 'default)
                                  svg-tag--font-weights))
         (char-width   (window-font-width))
         (char-height  (window-font-height))
         (text-width   (* char-width (length text)))
         (box-height   (- char-height 2))
         (tag-height   (- box-height (* border-width 2)))
         (tag-x        (+ margin border-width))
         (tag-y        (+ border-width 1))
         (total-width  (+ text-width (* padding 2) (* margin 2) (* border-width 2)))
         (svg-width    (if (= (mod total-width
                                   char-width)
                              0)
                           total-width
                         (* (+ 1
                               (truncate (/ total-width
                                            char-width)))
                            char-width)))
         (box-width    (- svg-width (* margin 2)))
         (tag-width    (- box-width (* border-width 2)))
         (text-size    (* (ceiling
                           (* (face-attribute face :height nil 'default)
                              0.1))
                          (image-compute-scaling-factor 'auto)))
         (text-x       (+ tag-x
                          padding
                          (/ (- tag-width
                                (* padding 2)
                                (* (/ (float char-width)
                                      char-height)
                                   (* (/ text-size
                                         3.0)
                                      4)
                                   (length text)))
                             2)))
         (text-y       (+ text-size (/ (- box-height
                                          (* (/ text-size 3.0)
                                             4))
                                       2)
                          border-width))
         (svg         (svg-create svg-width char-height)))
    (svg-rectangle svg margin 1 box-width box-height
                   :fill (if box border-color background)
                   :rx   radius)
    (when box
      (svg-rectangle svg
                     tag-x tag-y tag-width tag-height
                     :fill background
                     :rx   radius))
    (svg-text svg text
              :font-family font-family
              :font-weight font-weight
              :font-size   text-size
              :fill        foreground
              :x           text-x
              :y           text-y)
    (svg-image svg :scale 1 :ascent 'center)))
```

**Comment by rougier** [comment]
Thansk. It still doesn't look right on my machine:

Screenshot 2021-12-16 at 14 31 09

**Comment by aru-hackZ** [comment]
The tag is the 'hello' that seems like it is bold? Then I would like to know your `default` face properties since maybe there is something im not taking in account when calculating the tag text size.

**Comment by rougier** [comment]
I'm using "Roboto Mono" with light weight. Also, note that the tag is also a bit off (baseline doesn't match regular text).  You can check [svg-lib.el](https://github.com/rougier/svg-lib/blob/master/svg-lib.el#L232) to see how I compute the ascent.

**Comment by aru-hackZ** [comment]
"Nicolas P. Rougier" ***@***.***> writes:

> I'm using "Roboto Mono" with light weight. Also, note that the tag is also a bit off (baseline doesn't
> match regular text). You can check svg-lib.el to see how I compute the ascent.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.

Is the `tag-char-width` the width of the characters *inside* the tag? If
it is, that's a better way than calculating it with what I did:

```
(* (/ (float char-width)
      char-height)
   (* (/ text-size
         3.0)
      4))
```

I will be testing it all tomorrow, because actually I didn't know you
could get that info from `font-info`, and when I understand it I may be
able to adapt my text aligning to the center in your svg-lib mode, which
seems to have better calculations than svg-tags (in the sense of it may
work in more screens)

------
By aru

**Pull request closed without merging**
