### PR TITLE
Add day name matching to example

### PR DESCRIPTION
**Pull request by xav-ie**
I futzed for a couple of hours and finally figured out how to get day names also matched. I like having the day names and that is added by default (I think) anyways for when you mark something done.

It looks really nice! Please add this so others will not have to struggle like me :)

image

### CODE REVIEW

**Comment by rougier** [comment]
Nice, thank you. Could sign the [Emacs Copyright Assignment](https://www.gnu.org/software/emacs/manual/html_node/emacs/Copyright-Assignment.html) such that I can merge your PR?

**Comment by rougier** [comment]
I forgot: there seems to be a lot of spaces around dates in your screenshot. Was it already the case without your PR?

**Comment by chraibi** [comment]
@xav-ie thanks man! You are a life-saver :-)

**Comment by rougier** [comment]
Thanks!

**Pull request merged**
