### PR TITLE
fix: update README to solve issue #27

### PR DESCRIPTION
**Pull request by Elilif**

### CODE REVIEW

**Comment by rougier** [comment]
Thanks for this long awaited bugfix. Sorry if you already answered me but did you sign the copyright assignment form (such that I can merge)?

**Comment by rougier** [comment]
@Elilif Did  you signed the copyright assignment?

**Comment by Elilif** [comment]
> @Elilif Did you signed the copyright assignment?

I have sent the email to [assign@gnu.org](mailto:assign@gnu.org) , and waiting for a response.

**Comment by Elilif** [comment]
> @Elilif Did you signed the copyright assignment?

I have signed the copyright assignment.

**Comment by rougier** [comment]
Many thanks!

**Pull request merged**
